version: '3.5'


volumes:
  nats_data:

networks:
  bit-price-network:
    name: bit-price-network
    external: true

services:
  nats:
    image: nats:latest
    container_name: nats_server_dev
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_SERVER_OPTS=-js -t ${NATS_TOKEN}
    volumes:
      - nats_data:/data
    networks:
      - bit-price-network
