version: '3.5'

networks:
  bit-price-network:
    name: bit-price-network
    external: true

volumes:
  logs:

services:
  collector_app_dev:
    env_file: .env.dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - logs:/var/logs/
    networks:
      - bit-price-network
    ports:
      - 12345:12345