version: '3.5'

networks:
  bit-price-network:
    name: bit-price-network
    external: true

volumes:
  logs:

services:
  collector_app:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - API_CMC=${API_CMC}
      - NATS_HOST=${NATS_HOST}
      - NATS_PORT=${NATS_PORT}
      - NATS_TOKEN=${NATS_TOKEN}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - logs:/var/logs/
    networks:
      - bit-price-network